models/Address.php
<?php


namespace app\models;


use yii\db\ActiveRecord;
use app\models\Users;

class Address extends ActiveRecord
{
    public static function tableName(){
        return 'addresses';
    }

    public function rules()
    {

        return [
            [['post_index', 'country', 'city','street','house_number'], 'required'],
            ['post_index', 'match', 'pattern' => '/[0-9]/', 'message' => 'This field should be filling numbers'],
            ['country', 'string', 'max' => 2],
            ['country', 'match', 'pattern' => '/[A-Z]{2}/', 'message' => 'This field should be filling Uppercase'],
            ['office','default', 'value' => null]
        ];

    }

    public function getUser()
    {
        return $this->hasOne(Users::className(), ['id' => 'user_id']);
    }
}

models/Users.php
<?php

namespace app\models;
use yii\db\ActiveRecord;
use app\models\Address;

class Users extends ActiveRecord
{
    public $address;

    const MALE = 1;
    const FEMALE = 2;
    const UNDEFINEND = 0;

    public static function tableName(){
        return 'users';
    }

    public function rules(){
        return [
            [['login', 'password', 'firstname','lastname','gender','date', 'email'], 'required'],
            [['login', 'email'], 'unique', 'message' => 'The field should be unique'],
            ['login', 'string', 'min' => 4],
            ['password', 'string', 'min' => 6],
            [['firstname','lastname'], 'match', 'pattern' => '/[A-Z][a-zA-Z]*\s*/', 'message' => 'This field should be filling Capitalize'],
            ['email','email']
        ];
    }

    public function getAdress()
    {
        return $this->hasMany(Address::className(), ['user_id' => 'id']);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;
use yii\web\Controller;

class SiteController extends Controller
{
    public function actionIndex(){
        return $this->render('index');
    }
}

controllers/UserController.php
<?php


namespace app\controllers;


use app\models\Address;
use yii\data\Pagination;
use yii\db\Query;
use yii\web\Controller;
use app\models\Users;
use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\base\Model;
use yii\web\User;
use yii\widgets\ActiveForm;

class UserController extends Controller
{
    public function actionAdduser(){
          $model = new Users();
          $address = new Address();

          $addressFields = $this->getAddressFields();

          if($model->load(Yii::$app->request->post()) && $address->load(Yii::$app->request->post())){
                $post_data = Yii::$app->request->post();
              $transaction = Yii::$app->db->beginTransaction();
              try  {
                  if ($model->save()) {
                      foreach ($post_data['Address'] as $post_val){
                          Yii::$app->db->createCommand()->insert('addresses', [
                              'user_id' => $model->id,
                              'post_index' => $post_val['post_index'],
                              'country' => $post_val['country'],
                              'city' => $post_val['city'],
                              'street' => $post_val['street'],
                              'house_number' => $post_val['house_number'],
                              'office' => $post_val['office'],
                          ])->execute();
                      }
                      $transaction->commit();
                      Yii::$app->session->setFlash('success', 'User added');
                      return $this->refresh();
                  } else {
                      $transaction->rollBack();
                      Yii::$app->session->setFlash('error', 'Data error');
                  }
              } catch (Exception $e) {
                  $transaction->rollBack();
                  Yii::$app->session->setFlash('error', 'Data error2222');
              }
          }

        return $this->render('adduser', [
            'model' => $model,
            'address' => $address,
            'addressFields' => $addressFields,
            'index' => $index
        ]);
    }

    private function getAddressFields(){
        $address = new Address();
        $attrArr = $address->attributes;
        unset($attrArr['id']);
        unset($attrArr['user_id']);
        $attrArr = array_keys($attrArr);
        return $attrArr;
    }

    public function actionDeleteUser(){
        $userId = (int)\Yii::$app->request->post('userId');
        if($userId){
            $user = Users::findOne($userId);
            if(!empty($user)){
                if($user->delete()){
                    return true;
                }
            }
        }
        return false;
    }

    public function actionDeleteAddress(){
        $addressId = (int)\Yii::$app->request->post('addressId');
        if($addressId){
            $address = Address::findOne($addressId);
            if(!empty($address)){
                if($address->delete()){
                    return true;
                }
            }
        }
        return false;
    }

    public function actionUsers(){

        $users = Users::find()->all();

        $pagination = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => count($users),
        ]);


        return $this->render('users', [
            'models' => $users,
            'pagination' => $pagination
        ]);
    }

    public function actionUser($userId){

        $user = Users::findOne($userId);
        $model = new Users();
        $model->login = $user->login;
        $model->password = $user->password;
        $model->firstname = $user->firstname;
        $model->lastname = $user->lastname;
        $model->gender = $user->gender;
        $model->date = $user->date;
        $model->email = $user->email;

        if($model->load(\Yii::$app->request->post())){

            if($model->save()){
                \Yii::$app->session->setFlash('success', 'User edited');
                return $this->refresh();
            }else{
                \Yii::$app->session->setFlash('error', 'Data error');
            }

        }

        return $this->render('user', ['user'=>$user, 'model' => $model]);
    }

    public function actionDublicateAddress($index){
        $address = new Address();
        $model = new Users();
        $addressFields = $this->getAddressFields();

        return $this->renderAjax('_addfields',[
            'model' => $model,
            'address' => $address,
            'addressFields' => $addressFields,
            'index' => $index
        ]);
    }

    public function actionAddresses($userId){
        $addresses = Address::find()->where(['user_id' => $userId])->all();

        return $this->render('useraddresses',[
            'addresses' => $addresses
        ]);
    }

    public function actionAddress($addressId){

        $address = Address::findOne($addressId);
        $model = new Address();
        $model->post_index = $address->post_index;
        $model->country = $address->country;
        $model->city = $address->city;
        $model->street = $address->street;
        $model->house_number = $address->house_number;
        $model->office = $address->office;

        if($model->load(\Yii::$app->request->post())){

            if($model->save()){
                \Yii::$app->session->setFlash('success', 'Address edited');
                return $this->refresh();
            }else{
                \Yii::$app->session->setFlash('error', 'Data error');
            }

        }

        return $this->render('address', ['address'=>$address, 'model' => $model]);
    }

    public function actionAddAddress($userId){

        $address = new Address();

        if($address->load(\Yii::$app->request->post())){
            $address->user_id = $_GET['userId'];

            if($address->save()){
                \Yii::$app->session->setFlash('success', 'Address added');
                return $this->refresh();
            }else{
                \Yii::$app->session->setFlash('error', 'Data error');
            }

        }

        return $this->render('addaddress',[
            'model' => $address
        ]);
    }


}

views/layouts/main.php
<?php $this->beginPage();

use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use app\assets\AppAsset;use yii\helpers\Html;
?>
<html>
<head>
    <?= Html::csrfMetaTags() ?>
    <title>Bintime test</title>
    <?php AppAsset::register($this); ?>
    <?php $this->head(); ?>
</head>
<body>
<?php $this->beginBody(); ?>
<?php
    \yii\bootstrap\NavBar::begin([
            'brandLabel' => 'Bintime',
            'brandUrl' => Yii::$app->homeUrl,
            'options' => [
                    'class' => 'navbar-default navbar-fixed-top'
            ]
    ]);
    $items = [
        ['label' => 'AddUser', 'url' => ['/user/adduser']],
        ['label' => 'Users', 'url' => ['/user/users']]
    ];
    echo \yii\bootstrap\Nav::widget([
            'options' => ['class' => 'navbar-nav'],
            'items' => $items
    ]);
    \yii\bootstrap\NavBar::end();
    ?>
    <div class="container main_container">
        <?= $content?>
    </div>
<?php AppAsset::register($this); ?>
<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>

views/site/index.php
<h1 class="center">To perform an action - click on the appropriate section of the menu</h1>

views/user/_addfields.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\widgets\Pjax;
?>
        <div class="add_address">
            <div class="form-group field-address-<?=$index?>-post_index required">
                <label class="control-label" for="address-<?=$index?>-post_index">Post Index</label>
                <input type="text" id="address-<?=$index?>-post_index" class="form-control" name="Address[<?=$index?>][post_index]">

                <div class="help-block"></div>
            </div><div class="form-group field-address-<?=$index?>-country required">
                <label class="control-label" for="address-<?=$index?>-country">Country</label>
                <input type="text" id="address-<?=$index?>-country" class="form-control" name="Address[<?=$index?>][country]">

                <div class="help-block"></div>
            </div><div class="form-group field-address-<?=$index?>-city required">
                <label class="control-label" for="address-<?=$index?>-city">City</label>
                <input type="text" id="address-<?=$index?>-city" class="form-control" name="Address[<?=$index?>][city]">

                <div class="help-block"></div>
            </div><div class="form-group field-address-<?=$index?>-street required">
                <label class="control-label" for="address-<?=$index?>-street">Street</label>
                <input type="text" id="address-<?=$index?>-street" class="form-control" name="Address[<?=$index?>][street]">

                <div class="help-block"></div>
            </div><div class="form-group field-address-<?=$index?>-house_number required">
                <label class="control-label" for="address-<?=$index?>-house_number">House Number</label>
                <input type="text" id="address-<?=$index?>-house_number" class="form-control" name="Address[<?=$index?>][house_number]">

                <div class="help-block"></div>
            </div><div class="form-group field-address-<?=$index?>-office required">
                <label class="control-label" for="address-<?=$index?>-office">Office</label>
                <input type="text" id="address-<?=$index?>-office" class="form-control" name="Address[<?=$index?>][office]">

                <div class="help-block"></div>
            </div>                </div>
        </div>

views/user/addAddress.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>
<?php if(Yii::$app->session->hasFlash('success')) :?>
    <div class="alert alert-success" role="alert">
        <?php echo Yii::$app->session->getFlash('success'); ?>
    </div>
<?php endif; ?>
<?php if(Yii::$app->session->hasFlash('error')) :?>
    <div class="alert alert-danger" role="alert">
        <?php echo Yii::$app->session->getFlash('error');?>
    </div>
<?php endif; ?>
<div class="panel panel-info">
    <div class="panel-heading">
        <h1>Add address</h1>
    </div>
    <div class="panel-body">
        <?php $form = ActiveForm::begin([
            'id' => 'user-add'
        ]) ?>
        <? echo $form->field($model, 'user_id')->hiddenInput(['value' => $_GET['userId']]); ?>
        <?= $form->field($model, 'post_index')?>
        <?= $form->field($model, 'country')?>
        <?= $form->field($model, 'city')?>
        <?= $form->field($model, 'street')?>
        <?= $form->field($model, 'house_number')?>
        <?= $form->field($model, 'office')?>
        <?=Html::submitButton('Add address', ['class' => 'btn btn-success'])?>
        <?php ActiveForm::end() ?>
    </div>
</div>

views/user/addUser.php
<?php
    use yii\widgets\ActiveForm;
    use yii\helpers\Html;
    use yii\widgets\Pjax;
?>
<?php if(Yii::$app->session->hasFlash('success')) :?>
    <div class="alert alert-success" role="alert">
        <?php echo Yii::$app->session->getFlash('success'); ?>
    </div>
<?php endif; ?>
<?php if(Yii::$app->session->hasFlash('error')) :?>
    <div class="alert alert-danger" role="alert">
        <?php echo Yii::$app->session->getFlash('error');?>
    </div>
<?php endif; ?>
<div class="panel panel-info">
        <div class="panel-heading">
            <h1>Add user</h1>
        </div>
        <div class="panel-body">
                <?php $form = ActiveForm::begin([
                        'id' => 'user-add'
                ]) ?>
                    <?= $form->field($model, 'login')?>
                    <?= $form->field($model, 'password')->passwordInput()?>
                    <?= $form->field($model, 'firstname')?>
                    <?= $form->field($model, 'lastname')?>
                    <?php $model->gender = $model::UNDEFINEND?>
                    <?= $form->field($model, 'gender')
                    ->radioList(
                            [$model::MALE => 'Male', $model::FEMALE => 'Female', $model::UNDEFINEND => 'Undefined']
                    )->label('Gender');
                   ?>
                   <?php $model->date = date('d-m-Y H:i') ?>
                    <?= $form->field($model, 'date')->textInput(['readonly' => true])?>
                    <?= $form->field($model, 'email')->input('email')?>
            <p class="add_address_head">Add address</p>

            <div class="addresses">
                <div class="add_address">
                    <?php    foreach ($addressFields as $field):
                        echo   $form->field($address, "[0]$field");
                    endforeach; ?>
                </div>
            </div>
            <p class="add_more_address">
            <?php
                echo Html::a('Добавить адрес', ['', 'index' => $index], [
                    'class' => 'btn btn-primary js-add-address',
                ]);
            ?>
            </p>

                    <?=Html::submitButton('Add user', ['class' => 'btn btn-success'])?>
                <?php ActiveForm::end() ?>
        </div>
</div>
<?php
$modalAuthReg = <<< JS

$('.js-add-address').on('click', function(){
    var index = $('.add_address').length;
        $.ajax({
            url: "/user/dublicate-address?index=" + index,

            success: function(data) {
                $('.addresses').append(data)
            },
            error: function () {
                alert('error');
            }
        });
        return false;
    });
JS;


$this->registerJs($modalAuthReg, \yii\web\View::POS_LOAD);

views/user/address.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>
<?php if(Yii::$app->session->hasFlash('success')) :?>
    <div class="alert alert-success" role="alert">
        <?php echo Yii::$app->session->getFlash('success'); ?>
    </div>
<?php endif; ?>
<?php if(Yii::$app->session->hasFlash('error')) :?>
    <div class="alert alert-danger" role="alert">
        <?php echo Yii::$app->session->getFlash('error');?>
    </div>
<?php endif; ?>
<div class="panel panel-info">
    <div class="panel-heading">
        <h1>Edit Address <?php echo $user->firstname.' '. $user->lastname?></h1>
    </div>
    <div class="panel-body">
        <?php $form = ActiveForm::begin() ?>
        <?= $form->field($model, 'post_index')?>
        <?= $form->field($model, 'country')?>
        <?= $form->field($model, 'city')?>
        <?= $form->field($model, 'street')?>
        <?= $form->field($model, 'house_number')?>
        <?= $form->field($model, 'office')?>
        <?=Html::submitButton('Edit user', ['class' => 'btn btn-success'])?>
        <?php ActiveForm::end() ?>
    </div>
    <div>
        <a href="#">User addresses</a>
    </div>
</div>

views/user/user.php
<?php
    use yii\widgets\ActiveForm;
    use yii\helpers\Html;
?>
<?php if(Yii::$app->session->hasFlash('success')) :?>
    <div class="alert alert-success" role="alert">
        <?php echo Yii::$app->session->getFlash('success'); ?>
    </div>
<?php endif; ?>
<?php if(Yii::$app->session->hasFlash('error')) :?>
    <div class="alert alert-danger" role="alert">
        <?php echo Yii::$app->session->getFlash('error');?>
    </div>
<?php endif; ?>
<div class="panel panel-info">
    <div class="panel-heading">
        <h1>Edit User <?php echo $user->firstname.' '. $user->lastname?></h1>
    </div>
    <div class="panel-body">
        <?php $form = ActiveForm::begin() ?>
        <?= $form->field($model, 'login')?>
        <?= $form->field($model, 'password')->passwordInput()?>
        <?= $form->field($model, 'firstname')?>
        <?= $form->field($model, 'lastname')?>
        <?php $model->gender = $model::UNDEFINEND?>
        <?= $form->field($model, 'gender')
            ->radioList(
                [$model::MALE => 'Male', $model::FEMALE => 'Female', $model::UNDEFINEND => 'Undefined']
            )->label('Gender');
        ?>
        <?php $model->date = date('d-m-Y H:i') ?>
        <?= $form->field($model, 'date')->textInput(['readonly' => true])?>
        <?= $form->field($model, 'email')->input('email')?>
        <?=Html::submitButton('Edit user', ['class' => 'btn btn-success'])?>
        <?php ActiveForm::end() ?>
    </div>
    <div>
        <a href="/user/addresses?userId=<?=$user->id?>">User addresses</a>
    </div>
</div>

views/user/userAddresses.php
<?php
    use yii\widgets\LinkPager;

?>

<h1>User addresses</h1>
<ul class="address_list">
    <?php foreach ($addresses as $address): ?>
        <li>
            <?php
            echo $address->country.' '.$address->city;
            ?>
            <p>
                <a href="<?php echo '/user/address?addressId='.$address->id ?>" class="btn">Edit address</a>
                <a href="#" class="delete_address" data-address-id="<?=$address->id?>">Delete address</a>

            </p>

        </li>
    <?php endforeach; ?>
</ul>

<div class="add_new_address">
    <a href="/user/add-address?userId=<?=$_GET['userId']?>" class="add_new_address">Add new address</a>
</div>

views/user/users.php
<?php
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\widgets\Pjax;
use yii\grid\GridView;
?>
<h1>Users</h1>
<ul class="users_list">
    <?php foreach ($models as $user): ?>
        <li>
            <?php
                echo $user->firstname.' '.$user->lastname;
            ?>
            <p>
                <a href="<?php echo '/user/user?userId='.$user->id ?>" class="btn">Edit user</a>
                <a href="#" class="delete_user" data-user-id="<?=$user->id?>">Delete user</a>

            </p>

        </li>
    <?php endforeach; ?>
</ul>

<?= LinkPager::widget(['pagination' => $pagination]) ?>